const AUTH_USER_KEY='entego_auth_user';
const AUTH_AFTER_KEY='entego_after_auth';
const AUTH_UI_VERSION='77';
const authRead=()=>{try{return JSON.parse(localStorage.getItem(AUTH_USER_KEY)||'null')}catch{return null}};
const authWrite=user=>user?localStorage.setItem(AUTH_USER_KEY,JSON.stringify(user)):localStorage.removeItem(AUTH_USER_KEY);
const authRoute=()=>localStorage.getItem('entego_route')||'home';
const authEsc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
const authRoleLabel=r=>r==='partner'?'Mitra':r==='admin'?'Admin':'Customer';
let authRefreshPromise=null;
function authMe(){
 if(authRefreshPromise)return authRefreshPromise;
 authRefreshPromise=(async()=>{try{const r=await fetch('/api/auth/me',{cache:'no-store',headers:{accept:'application/json'}});let d={};try{d=await r.json()}catch{}if(r.ok&&d.ok&&d.user){authWrite(d.user);return d.user}if(r.status===401){authWrite(null);return null}return authRead()}catch{return authRead()}})().finally(()=>{setTimeout(()=>{authRefreshPromise=null},750)});
 return authRefreshPromise;
}
async function authPost(path,body){
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);
 try{
  const r=await fetch(path,{method:'POST',cache:'no-store',headers:{'content-type':'application/json','accept':'application/json'},body:body?JSON.stringify(body):undefined,signal:controller.signal});
  let d={};try{d=await r.json()}catch{}
  if(!r.ok||!d.ok){const e=new Error(d.error||'request_failed');e.retryAfter=Number(d.retryAfter||r.headers.get('retry-after')||0);throw e}
  return d;
 }catch(e){if(e?.name==='AbortError')throw new Error('request_timeout');if(e instanceof TypeError)throw new Error('network_error');throw e}finally{clearTimeout(timer)}
}
function authMessage(code,retryAfter=0){
 if(code==='rate_limited')return `Terlalu banyak percobaan. Coba lagi dalam ${Math.max(1,Math.ceil(Number(retryAfter||60)/60))} menit.`;
 return ({INVALID_EMAIL:'Email tidak valid.',INVALID_PASSWORD:'Password minimal 8 karakter.',DISPLAY_NAME_REQUIRED:'Nama wajib diisi.',INVALID_ROLE:'Jenis akun tidak valid.',EMAIL_EXISTS:'Email sudah terdaftar. Silakan gunakan menu Masuk.',INVALID_CREDENTIALS:'Email atau password salah.',network_error:'Koneksi ke server ENTEGO gagal. Periksa internet lalu coba lagi.',request_timeout:'Server belum merespons. Coba lagi beberapa saat.',auth_server_error:'Server akun ENTEGO sedang bermasalah. Coba lagi beberapa saat.',customer_role_required:'Gunakan akun Customer untuk membuat booking.'})[code]||'Proses belum berhasil. Periksa data lalu coba lagi.';
}
function authPanel(){
 if(authRoute()!=='profile')return;const main=document.querySelector('main.content');if(!main||document.querySelector('#entegoAuthPanel'))return;const user=authRead(),box=document.createElement('section');box.id='entegoAuthPanel';box.className='card';
 if(user){box.innerHTML=`<div class="kicker">AKUN ENTEGO</div><div class="row between"><div><h2 style="margin:6px 0">${authEsc(user.displayName)}</h2><div class="meta">${authEsc(user.email)}</div></div><span class="pill green">${authRoleLabel(user.role)}</span></div><div style="margin-top:10px"><span class="pill ${user.verified?'green':'blue'}">${user.role==='partner'?(user.verified?'✓ Mitra terverifikasi':'Verifikasi identitas diperlukan'):'✓ Akun aktif'}</span></div><button class="btn soft" id="entegoLogout" style="width:100%;margin-top:14px">Keluar</button>`;main.prepend(box);box.querySelector('#entegoLogout').onclick=async()=>{try{await authPost('/api/auth/logout')}catch{}authWrite(null);localStorage.setItem('entego_route','home');location.reload()};return}
 box.innerHTML=`<div class="kicker">ENTEGO ACCOUNT</div><h2 style="margin:6px 0 4px">Masuk atau buat akun</h2><p class="meta">Akun diperlukan untuk booking dan dashboard mitra.</p><div class="tabbar" style="margin:12px 0"><button class="tab active" id="authLoginTab" type="button">Masuk</button><button class="tab" id="authRegisterTab" type="button">Daftar</button></div><div id="authError" class="meta" role="status" aria-live="polite" style="display:none;margin-bottom:10px"></div><div id="authLoginForm" class="form"><div class="field"><label>Email</label><input id="authLoginEmail" type="email" autocomplete="email" inputmode="email" placeholder="nama@email.com"></div><div class="field"><label>Password</label><input id="authLoginPassword" type="password" autocomplete="current-password" placeholder="Minimal 8 karakter"></div><button class="btn primary" id="authLoginBtn" type="button" style="width:100%">Masuk ENTEGO</button><div id="authLoginStatus" class="meta" role="status" aria-live="polite" style="display:none;margin-top:10px;padding:10px 12px;border-radius:12px;background:#fff7ed;color:#9a3412"></div></div><div id="authRegisterForm" class="form" style="display:none"><div class="field"><label>Nama</label><input id="authDisplayName" autocomplete="name" placeholder="Nama kamu / nama talent"></div><div class="field"><label>Email</label><input id="authRegisterEmail" type="email" autocomplete="email" inputmode="email" placeholder="nama@email.com"></div><div class="field"><label>Password</label><input id="authRegisterPassword" type="password" autocomplete="new-password" minlength="8" maxlength="128" placeholder="Minimal 8 karakter"></div><div class="field"><label>Jenis akun</label><select id="authRegisterRole"><option value="customer">Customer</option><option value="partner">Mitra ENTEGO</option></select></div><button class="btn primary" id="authRegisterBtn" type="button" style="width:100%">Buat Akun</button><div id="authRegisterStatus" class="meta" role="status" aria-live="polite" style="display:none;margin-top:10px;padding:10px 12px;border-radius:12px;background:#fff7ed;color:#9a3412"></div><div class="meta" style="margin-top:8px;font-size:11px">Account UI v${AUTH_UI_VERSION}</div></div>`;main.prepend(box);
 const login=box.querySelector('#authLoginForm'),reg=box.querySelector('#authRegisterForm'),lt=box.querySelector('#authLoginTab'),rt=box.querySelector('#authRegisterTab'),err=box.querySelector('#authError'),loginStatus=box.querySelector('#authLoginStatus'),registerStatus=box.querySelector('#authRegisterStatus');
 const hideStatus=()=>{err.style.display='none';loginStatus.style.display='none';registerStatus.style.display='none'};
 const mode=m=>{const isLogin=m==='login';login.style.display=isLogin?'':'none';reg.style.display=isLogin?'none':'';lt.classList.toggle('active',isLogin);rt.classList.toggle('active',!isLogin);hideStatus()};lt.onclick=()=>mode('login');rt.onclick=()=>mode('register');
 const finish=user=>{authWrite(user);const after=localStorage.getItem(AUTH_AFTER_KEY);localStorage.removeItem(AUTH_AFTER_KEY);localStorage.setItem('entego_route',after||(user.role==='partner'?'partner':'profile'));location.reload()};
 const showFail=(e,target)=>{const msg=authMessage(e.message,e.retryAfter);err.textContent=msg;err.style.display='block';target.textContent=msg;target.style.display='block';target.scrollIntoView({behavior:'smooth',block:'nearest'})};
 box.querySelector('#authLoginBtn').onclick=async()=>{const b=box.querySelector('#authLoginBtn'),email=box.querySelector('#authLoginEmail').value.trim().toLowerCase(),password=box.querySelector('#authLoginPassword').value;hideStatus();if(!email){showFail(new Error('INVALID_EMAIL'),loginStatus);return}if(!password){showFail(new Error('INVALID_CREDENTIALS'),loginStatus);return}const original=b.textContent;b.disabled=true;b.textContent='Memeriksa akun…';try{const d=await authPost('/api/auth/login',{email,password});loginStatus.textContent='Login berhasil. Menyiapkan akun…';loginStatus.style.display='block';finish(d.user)}catch(e){showFail(e,loginStatus)}finally{b.disabled=false;b.textContent=original}};
 box.querySelector('#authRegisterBtn').onclick=async()=>{const b=box.querySelector('#authRegisterBtn'),displayName=box.querySelector('#authDisplayName').value.trim(),email=box.querySelector('#authRegisterEmail').value.trim().toLowerCase(),password=box.querySelector('#authRegisterPassword').value,role=box.querySelector('#authRegisterRole').value;hideStatus();if(!displayName){showFail(new Error('DISPLAY_NAME_REQUIRED'),registerStatus);return}if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){showFail(new Error('INVALID_EMAIL'),registerStatus);return}if(password.length<8||password.length>128){showFail(new Error('INVALID_PASSWORD'),registerStatus);return}if(!['customer','partner'].includes(role)){showFail(new Error('INVALID_ROLE'),registerStatus);return}const original=b.textContent;b.disabled=true;b.textContent='Membuat akun…';registerStatus.textContent='Menghubungkan ke server ENTEGO…';registerStatus.style.display='block';try{const d=await authPost('/api/auth/register',{displayName,email,password,role});registerStatus.textContent='Akun berhasil dibuat. Menyiapkan ENTEGO…';registerStatus.style.background='#ecfdf5';registerStatus.style.color='#166534';finish(d.user)}catch(e){showFail(e,registerStatus)}finally{b.disabled=false;b.textContent=original}};
}
function authGuardClick(e){const el=e.target.closest('[data-route]');if(!el)return;const target=el.dataset.route,user=authRead(),partnerRoutes=new Set(['partner','partnerOrders','partnerOrderDetail','partnerChat','partnerCalendar','partnerPackages','partnerPortfolio','partnerReviews','partnerWallet','partnerAnalytics']);if(partnerRoutes.has(target)&&(!user||!['partner','admin'].includes(user.role))){e.preventDefault();e.stopImmediatePropagation();localStorage.setItem(AUTH_AFTER_KEY,target);localStorage.setItem('entego_route','profile');location.reload();return}if(target==='admin'&&(!user||user.role!=='admin')){e.preventDefault();e.stopImmediatePropagation();localStorage.setItem(AUTH_AFTER_KEY,'admin');localStorage.setItem('entego_route','profile');location.reload()}}
document.addEventListener('click',authGuardClick,true);
const authRun=()=>authPanel();new MutationObserver(authRun).observe(document.documentElement,{childList:true,subtree:true});authRun();
const lowPriority=new Set(['home','explore','services','favorites']);const refresh=()=>authMe().then(authRun);if(lowPriority.has(authRoute())){if('requestIdleCallback'in window)requestIdleCallback(refresh,{timeout:1800});else setTimeout(refresh,700)}else refresh();
