const reasons=["Salah pilih layanan","Salah tanggal / jam","Lokasi acara berubah","Menemukan layanan lain","Acara dibatalkan","Lainnya"];
function injectCancelStyles(){if(document.getElementById('entego-cancel-style'))return;const s=document.createElement('style');s.id='entego-cancel-style';s.textContent=`
.cancel-overlay{position:fixed;inset:0;z-index:9999;background:rgba(15,23,42,.58);display:flex;align-items:flex-end;justify-content:center;padding:0}
.cancel-sheet{width:min(100%,480px);max-height:88vh;overflow:auto;background:#f8fafc;border-radius:28px 28px 0 0;padding:18px 18px calc(22px + env(safe-area-inset-bottom));box-shadow:0 -24px 60px rgba(15,23,42,.24)}
.cancel-handle{width:48px;height:5px;background:#cbd5e1;border-radius:99px;margin:0 auto 16px}.cancel-sheet h2{margin:0 0 6px}.cancel-sheet p{color:#64748b;font-size:13px;line-height:1.5}
.cancel-policy{background:#fff;border:1px solid #e2e8f0;border-radius:18px;padding:14px;margin:14px 0}.cancel-policy b{display:block;margin-bottom:4px}.cancel-policy.green{background:#f0fdf4;border-color:#bbf7d0}.cancel-policy.orange{background:#fff7ed;border-color:#fed7aa}.cancel-policy.red{background:#fef2f2;border-color:#fecaca}
.cancel-reasons{display:grid;gap:8px;margin:12px 0}.cancel-reason{display:flex;align-items:center;gap:10px;background:#fff;border:1px solid #e2e8f0;border-radius:15px;padding:12px;font-size:13px;font-weight:700}.cancel-reason input{accent-color:#f97316}
.cancel-actions{display:flex;gap:10px;margin-top:16px}.cancel-actions button{flex:1;border:0;border-radius:14px;padding:13px;font-weight:800}.cancel-back{background:#fff;border:1px solid #e2e8f0!important;color:#0f172a}.cancel-confirm{background:#ef4444;color:#fff}.cancel-confirm:disabled{opacity:.45}
.cancel-status{background:#fff;border:1px solid #e2e8f0;border-radius:18px;padding:16px;text-align:center}.cancel-status .ok{width:58px;height:58px;border-radius:50%;display:grid;place-items:center;margin:0 auto 12px;background:#dcfce7;color:#15803d;font-size:30px;font-weight:900}
`;document.head.appendChild(s)}
function policy(){const started=localStorage.getItem('entego_event_started')==='1';const accepted=localStorage.getItem('entego_booking_status')==='diterima';if(started)return{type:'red',title:'Pekerjaan sudah dimulai',body:'Order tidak dapat dibatalkan secara normal. Gunakan Bantuan / Dispute agar tim ENTEGO meninjau kasus ini.',blocked:true};if(accepted)return{type:'orange',title:'Mitra sudah menerima order',body:'Pembatalan tetap dapat diajukan. Refund mengikuti kebijakan pembatalan dan biaya yang sudah timbul. Ringkasan refund akan ditampilkan sebelum konfirmasi.',blocked:false,refund:'Refund estimasi: Rp1.282.500 setelah biaya pembatalan.'};return{type:'green',title:'Mitra belum menerima order',body:'Pembatalan dapat dilakukan langsung. Pembayaran akan dikembalikan penuh sesuai metode pembayaran yang digunakan.',blocked:false,refund:'Refund penuh: Rp1.425.000.'}}
function closeSheet(){document.querySelector('.cancel-overlay')?.remove()}
function openCancellation(){injectCancelStyles();const p=policy();const overlay=document.createElement('div');overlay.className='cancel-overlay';overlay.innerHTML=`<div class="cancel-sheet"><div class="cancel-handle"></div><h2>Batalkan Order</h2><p>Order #ENT-260815-001 • Pilih alasan pembatalan sebelum melanjutkan.</p><div class="cancel-policy ${p.type}"><b>${p.title}</b><span>${p.body}</span>${p.refund?`<p style="margin:7px 0 0;font-weight:800;color:#0f172a">${p.refund}</p>`:''}</div>${p.blocked?`<button class="cancel-confirm" id="openDispute" style="width:100%;padding:13px;border-radius:14px;border:0;font-weight:800">Buka Bantuan / Dispute</button><div class="cancel-actions"><button class="cancel-back" id="cancelBack">Kembali</button></div>`:`<b style="font-size:13px">Alasan pembatalan</b><div class="cancel-reasons">${reasons.map((r,i)=>`<label class="cancel-reason"><input type="radio" name="cancelReason" value="${r}"> <span>${r}</span></label>`).join('')}</div><div class="cancel-actions"><button class="cancel-back" id="cancelBack">Kembali</button><button class="cancel-confirm" id="confirmCancel" disabled>Konfirmasi Pembatalan</button></div>`}</div>`;document.body.appendChild(overlay);overlay.querySelector('#cancelBack')?.addEventListener('click',closeSheet);overlay.addEventListener('click',e=>{if(e.target===overlay)closeSheet()});overlay.querySelectorAll('input[name="cancelReason"]').forEach(x=>x.addEventListener('change',()=>overlay.querySelector('#confirmCancel').disabled=false));overlay.querySelector('#confirmCancel')?.addEventListener('click',()=>{const reason=overlay.querySelector('input[name="cancelReason"]:checked')?.value||'Lainnya';localStorage.setItem('entego_cancel_reason',reason);localStorage.setItem('entego_cancelled','1');localStorage.setItem('entego_completed','0');localStorage.setItem('entego_route','orders');localStorage.setItem('entego_refund_status',localStorage.getItem('entego_booking_status')==='diterima'?'Diproses sesuai kebijakan':'Refund penuh diproses');overlay.querySelector('.cancel-sheet').innerHTML=`<div class="cancel-status"><div class="ok">✓</div><h2>Order Dibatalkan</h2><p>${reason}</p><div class="cancel-policy green"><b>Status Refund</b><span>${localStorage.getItem('entego_refund_status')}</span></div><button class="cancel-confirm" id="backOrders" style="width:100%">Lihat Order</button></div>`;overlay.querySelector('#backOrders').addEventListener('click',()=>location.reload())});overlay.querySelector('#openDispute')?.addEventListener('click',()=>{closeSheet();document.querySelector('[data-route="help"]')?.click()||alert('Buka menu Akun → Bantuan & keamanan untuk mengajukan dispute.')})}
document.addEventListener('click',e=>{const btn=e.target.closest('#cancelOrder');if(!btn)return;e.preventDefault();e.stopImmediatePropagation();openCancellation()},true);
