const q=(s,r=document)=>r.querySelector(s);
function addCompletionStyles(){if(q('#entego-completion-style'))return;const s=document.createElement('style');s.id='entego-completion-style';s.textContent=`
.complete-card{background:#fff;border:1px solid #e2e8f0;border-radius:22px;padding:16px;margin:14px 0;box-shadow:0 8px 24px rgba(15,23,42,.05)}
.complete-card h3{margin:0 0 6px}.complete-card p{margin:0 0 14px;color:#64748b;font-size:13px;line-height:1.5}.complete-actions{display:flex;gap:10px}.complete-actions button{flex:1;border-radius:14px;padding:12px;font-weight:800;border:1px solid #e2e8f0;background:#fff;color:#0f172a}.complete-actions .primary{background:#f97316;color:#fff;border-color:#f97316}.complete-actions .danger{color:#b91c1c;background:#fff7f7;border-color:#fecaca}
.release-box{background:#f0fdf4;border:1px solid #bbf7d0;border-radius:18px;padding:14px;margin:12px 0}.release-box b{display:block;color:#166534;margin-bottom:4px}.release-box p{margin:0;color:#166534;font-size:12px}
.issue-sheet{position:fixed;inset:0;z-index:10020;background:rgba(15,23,42,.62);display:flex;align-items:flex-end;justify-content:center}.issue-card{width:min(100%,480px);background:#f8fafc;border-radius:28px 28px 0 0;padding:20px 18px calc(22px + env(safe-area-inset-bottom))}.issue-card h2{margin:0 0 6px}.issue-card p{color:#64748b;font-size:13px;line-height:1.5}.issue-card textarea{width:100%;box-sizing:border-box;border:1px solid #e2e8f0;border-radius:14px;padding:12px;min-height:110px}.issue-actions{display:flex;gap:10px;margin-top:14px}.issue-actions button{flex:1;padding:13px;border-radius:14px;font-weight:800;border:1px solid #e2e8f0;background:#fff}.issue-actions .primary{background:#ef4444;color:#fff;border-color:#ef4444}
`;document.head.appendChild(s)}
function customerNeedsConfirmation(){return localStorage.getItem('entego_completed')==='1'&&localStorage.getItem('entego_cancelled')!=='1'&&localStorage.getItem('entego_customer_confirmed')!=='1'}
function customerConfirmed(){return localStorage.getItem('entego_customer_confirmed')==='1'}
function augmentCustomerCompletion(){if(localStorage.getItem('entego_route')!=='orderdetail')return;const main=q('main.content');if(!main||q('#completionCard'))return;addCompletionStyles();const box=document.createElement('div');box.id='completionCard';box.className='complete-card';if(customerNeedsConfirmation()){box.innerHTML=`<h3>Konfirmasi layanan selesai</h3><p>Mitra menandai pekerjaan telah selesai. Konfirmasi jika layanan sudah kamu terima dengan baik.</p><div class="complete-actions"><button class="danger" data-completion-action="issue">Ada Masalah</button><button class="primary" data-completion-action="confirm">Konfirmasi Selesai</button></div>`}else if(customerConfirmed()){box.innerHTML=`<div class="release-box"><b>✓ Layanan dikonfirmasi selesai</b><p>Konfirmasi customer sudah tercatat di perangkat. Settlement/payout mitra akan diaktifkan setelah payout backend production tersedia.</p></div><div class="complete-actions"><button data-completion-action="receipt">Bukti Transaksi</button><button class="primary" data-completion-action="review">Beri Ulasan</button></div>`}else return;main.appendChild(box)}
function augmentPartnerPayout(){if(!['partner','partnerOrderDetail','partnerWallet'].includes(localStorage.getItem('entego_route')))return;if(!customerConfirmed())return;const main=q('main.content');if(!main||q('#partnerPayoutReleased'))return;addCompletionStyles();const b=document.createElement('div');b.id='partnerPayoutReleased';b.className='release-box';b.innerHTML='<b>✓ Customer mengonfirmasi layanan</b><p>Status layanan sudah dikonfirmasi. Payout otomatis belum diaktifkan sampai settlement partner production tersedia.</p>';main.prepend(b)}
function openIssue(){addCompletionStyles();const o=document.createElement('div');o.className='issue-sheet';o.innerHTML=`<div class="issue-card"><h2>Laporkan Masalah</h2><p>Jelaskan kendala pada layanan. Status pembayaran/refund akan mengikuti proses server ENTEGO.</p><textarea id="issueText" placeholder="Contoh: mitra tidak menyelesaikan layanan sesuai paket..."></textarea><div class="issue-actions"><button id="closeIssue">Kembali</button><button class="primary" id="submitIssue">Kirim Laporan</button></div></div>`;document.body.appendChild(o);q('#closeIssue',o).onclick=()=>o.remove();o.addEventListener('click',e=>{if(e.target===o)o.remove()});q('#submitIssue',o).onclick=()=>{const txt=q('#issueText',o).value.trim();if(!txt)return alert('Tulis kendala terlebih dahulu.');localStorage.setItem('entego_dispute_open','1');localStorage.setItem('entego_dispute_note',txt);localStorage.setItem('entego_refund_status','Menunggu review');o.remove();localStorage.setItem('entego_route','help');location.reload()}}
function confirmCompletion(){localStorage.setItem('entego_customer_confirmed','1');localStorage.setItem('entego_refund_status','-');location.reload()}
function openReview(){const box=q('#entegoServerReview');if(box){box.scrollIntoView({behavior:'smooth',block:'center'});return}alert('Form ulasan server tersedia setelah status booking selesai tersinkron.')}
function augmentAll(){augmentCustomerCompletion();augmentPartnerPayout()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-completion-action]');if(!b)return;const a=b.dataset.completionAction;if(a==='confirm')confirmCompletion();if(a==='issue')openIssue();if(a==='review')openReview();if(a==='receipt')document.querySelector('[data-final-action="receipt"]')?.click()});
new MutationObserver(augmentAll).observe(document.documentElement,{subtree:true,childList:true});window.addEventListener('load',augmentAll);augmentAll();