const $=(s,r=document)=>r.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function addFinalStyles(){if($('#entego-final-flow-style'))return;const s=document.createElement('style');s.id='entego-final-flow-style';s.textContent=`
.final-info{background:#fff;border:1px solid #e2e8f0;border-radius:22px;padding:16px;margin:14px 0;box-shadow:0 8px 24px rgba(15,23,42,.05)}
.final-info h3{margin:0 0 10px;font-size:17px}.final-row{display:flex;justify-content:space-between;gap:14px;padding:8px 0;border-bottom:1px solid #eef2f7;font-size:13px}.final-row:last-child{border-bottom:0}.final-row span{color:#64748b}.final-row b{text-align:right;color:#0f172a}
.final-actions{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:12px}.final-actions button{border-radius:14px;padding:12px;border:1px solid #e2e8f0;background:#fff;font-weight:800;color:#0f172a}.final-actions .primary{background:#f97316;color:#fff;border-color:#f97316}
.partner-cancelled{background:#fff7ed;border:1px solid #fed7aa;border-radius:18px;padding:14px;margin:12px 0}.partner-cancelled b{display:block;color:#9a3412;margin-bottom:4px}.partner-cancelled p{margin:0;color:#7c2d12;font-size:13px;line-height:1.5}
.receipt-sheet{position:fixed;inset:0;z-index:10001;background:rgba(15,23,42,.62);display:flex;align-items:flex-end;justify-content:center}.receipt-card{width:min(100%,480px);max-height:90vh;overflow:auto;background:#f8fafc;border-radius:28px 28px 0 0;padding:20px 18px calc(22px + env(safe-area-inset-bottom))}.receipt-card h2{margin:0}.receipt-brand{display:flex;align-items:center;gap:10px;margin-bottom:18px}.receipt-brand img{width:46px;height:46px;border-radius:14px}.receipt-actions{display:flex;gap:10px;margin-top:16px}.receipt-actions button{flex:1;padding:13px;border-radius:14px;font-weight:800;border:1px solid #e2e8f0;background:#fff}.receipt-actions .primary{background:#f97316;color:#fff;border-color:#f97316}
`;document.head.appendChild(s)}
function toast(msg){let t=$('#entegoToast');if(t)t.remove();t=document.createElement('div');t.id='entegoToast';t.textContent=msg;t.style.cssText='position:fixed;z-index:12000;left:50%;bottom:94px;transform:translateX(-50%);background:#0f172a;color:#fff;padding:11px 15px;border-radius:999px;font-size:12px;font-weight:800;box-shadow:0 12px 30px rgba(15,23,42,.25)';document.body.appendChild(t);setTimeout(()=>t.remove(),2200)}
function openReceipt(){addFinalStyles();const cancelled=localStorage.getItem('entego_cancelled')==='1',completed=localStorage.getItem('entego_completed')==='1',method=localStorage.getItem('entego_pay')||'QRIS',reason=localStorage.getItem('entego_cancel_reason')||'-',refund=localStorage.getItem('entego_refund_status')||'-';const status=cancelled?'Dibatalkan':completed?'Selesai':'Aktif';const o=document.createElement('div');o.className='receipt-sheet';o.innerHTML=`<div class="receipt-card"><div class="receipt-brand"><img src="/logo-header.png?v=16"><div><h2>ENTEGO</h2><small>Bukti Transaksi</small></div></div><div class="final-info"><div class="final-row"><span>Order ID</span><b>#ENT-260815-001</b></div><div class="final-row"><span>Layanan</span><b>DJ Raka Bali</b></div><div class="final-row"><span>Tanggal</span><b>15 Agustus 2026 • 19:00</b></div><div class="final-row"><span>Lokasi</span><b>Seminyak, Bali</b></div><div class="final-row"><span>Pembayaran</span><b>${esc(method)}</b></div><div class="final-row"><span>Total</span><b>Rp1.425.000</b></div><div class="final-row"><span>Status</span><b>${status}</b></div>${cancelled?`<div class="final-row"><span>Alasan batal</span><b>${esc(reason)}</b></div><div class="final-row"><span>Refund</span><b>${esc(refund)}</b></div>`:''}</div><div class="receipt-actions"><button id="closeReceipt">Tutup</button><button class="primary" id="saveReceipt">Simpan Bukti</button></div></div>`;document.body.appendChild(o);o.addEventListener('click',e=>{if(e.target===o||e.target.id==='closeReceipt')o.remove()});$('#saveReceipt',o).onclick=()=>{const text=`ENTEGO - Bukti Transaksi\nOrder: #ENT-260815-001\nLayanan: DJ Raka Bali\nTanggal: 15 Agustus 2026 19:00\nLokasi: Seminyak, Bali\nPembayaran: ${method}\nTotal: Rp1.425.000\nStatus: ${status}${cancelled?`\nAlasan batal: ${reason}\nRefund: ${refund}`:''}`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/plain'}));a.download='ENTEGO-ENT-260815-001.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Bukti transaksi disimpan')};}
function augmentOrderDetail(){if(localStorage.getItem('entego_route')!=='orderdetail')return;const main=$('main.content');if(!main||$('#finalOrderInfo'))return;const cancelled=localStorage.getItem('entego_cancelled')==='1',completed=localStorage.getItem('entego_completed')==='1';const box=document.createElement('div');box.id='finalOrderInfo';box.className='final-info';if(cancelled){box.innerHTML=`<h3>Ringkasan Pembatalan</h3><div class="final-row"><span>Alasan</span><b>${esc(localStorage.getItem('entego_cancel_reason')||'Tidak disebutkan')}</b></div><div class="final-row"><span>Status refund</span><b>${esc(localStorage.getItem('entego_refund_status')||'Sedang diproses')}</b></div><div class="final-row"><span>Metode refund</span><b>${esc(localStorage.getItem('entego_pay')||'Metode pembayaran awal')}</b></div><div class="final-actions"><button data-final-action="help">Bantuan</button><button class="primary" data-final-action="rebook">Pesan Ulang</button></div>`}else{box.innerHTML=`<h3>Dokumen Order</h3><div class="final-row"><span>Status</span><b>${completed?'Selesai':'Aktif'}</b></div><div class="final-actions"><button data-final-action="receipt">Bukti Transaksi</button><button class="primary" data-final-action="chat">Hubungi Mitra</button></div>`}main.appendChild(box)}
function augmentCancelledList(){if(localStorage.getItem('entego_route')!=='orders'||localStorage.getItem('entego_cancelled')!=='1')return;if(!document.body.textContent.includes('Booking dibatalkan'))return;const card=$('main.content .card');if(!card||card.querySelector('[data-final-action="receipt"]'))return;const actions=document.createElement('div');actions.className='final-actions';actions.innerHTML='<button data-final-action="receipt">Bukti</button><button class="primary" data-final-action="rebook">Pesan Ulang</button>';card.appendChild(actions)}
function augmentPartner(){if(localStorage.getItem('entego_cancelled')!=='1')return;const route=localStorage.getItem('entego_route');if(!['partner','partnerOrders','partnerOrderDetail'].includes(route))return;const main=$('main.content');if(!main||$('.partner-cancelled'))return;const n=document.createElement('div');n.className='partner-cancelled';n.innerHTML=`<b>Order dibatalkan customer</b><p>#ENT-260815-001 tidak lagi aktif. Alasan: ${esc(localStorage.getItem('entego_cancel_reason')||'Tidak disebutkan')}. Jangan mulai pekerjaan untuk order ini.</p>`;main.prepend(n);if(route==='partnerOrderDetail'){main.querySelectorAll('#acceptOrder,#startEvent,#completeEvent').forEach(x=>x.remove())}}
function augment(){addFinalStyles();augmentOrderDetail();augmentCancelledList();augmentPartner()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-final-action]');if(!b)return;const a=b.dataset.finalAction;if(a==='receipt')openReceipt();if(a==='rebook'){localStorage.setItem('entego_cancelled','0');localStorage.setItem('entego_completed','0');localStorage.setItem('entego_event_started','0');localStorage.setItem('entego_booking_status','baru');localStorage.setItem('entego_route','detail');location.reload()}if(a==='help'){localStorage.setItem('entego_route','help');location.reload()}if(a==='chat'){localStorage.setItem('entego_route','chatCustomer');location.reload()}});
new MutationObserver(()=>augment()).observe(document.documentElement,{subtree:true,childList:true});
window.addEventListener('load',augment);augment();
