
import "./styles.css";
const state={route:"home",selectedVendor:null,categories:[["🎧","DJ"],["🎤","MC"],["🎸","Live Band"],["🎙️","Singer"],["📸","Fotografer"],["🎥","Videografer"],["🔊","Sound System"],["💡","Lighting"],["🚘","Mobil"],["🛵","Motor"],["🎪","Tenda"],["✨","Dekorasi"]],vendors:[
{id:1,emoji:"🎧",name:"DJ Raka Bali",cat:"DJ",price:"Rp1.500.000",rating:"4.9",loc:"Seminyak • 3,2 km"},
{id:2,emoji:"🎸",name:"Sunset Groove",cat:"Live Band",price:"Rp2.800.000",rating:"4.8",loc:"Canggu • 5,1 km"},
{id:3,emoji:"🔊",name:"Bali Pro Sound",cat:"Sound System",price:"Rp900.000",rating:"4.7",loc:"Denpasar • 7,4 km"},
{id:4,emoji:"📸",name:"Nusa Visual",cat:"Fotografer",price:"Rp1.200.000",rating:"4.9",loc:"Kuta • 4,6 km"}]};
const app=document.querySelector("#app"),icon=n=>`<b>${n}</b>`;
function topbar(title="ENTEGO",search=true,back=false){return `<div class="topbar"><div class="brand"><div class="${back?"page-title":"brandmark"}">${back?`<button class="back" data-route="home">‹</button>`:`<div class="logo">E</div>`}<span>${title}</span></div><button class="iconbtn" data-route="notifications">🔔</button></div>${search?`<div class="search"><input placeholder="Cari DJ, sound, mobil, MC..."><button data-route="explore">Cari</button></div>`:""}</div>`}
function bottom(active){return `<nav class="bottom">${[["⌂","home","Home"],["⌕","explore","Cari"],["▣","orders","Order"],["♥","favorites","Favorit"],["☺","profile","Akun"]].map(([i,r,l])=>`<button class="navbtn ${active===r?"active":""}" data-route="${r}">${icon(i)}${l}</button>`).join("")}</nav>`}
function vendorCard(v){return `<div class="vendor" data-vendor="${v.id}"><div class="vendor-img">${v.emoji}</div><div class="vendor-body"><div class="row between"><span class="pill">${v.cat}</span><span class="rating">★ ${v.rating}</span></div><h3>${v.name}</h3><div class="meta">${v.loc}</div><div class="row between" style="margin-top:10px"><b>${v.price}</b><span class="pill green">✓ Terverifikasi</span></div></div></div>`}
function home(){return `<div class="phone">${topbar()}<main class="content"><section class="hero"><small>ENTEGO • Bali</small><h1>Semua kebutuhan event dalam satu aplikasi.</h1><p>Booking talent & rental terpercaya, cepat dan transparan.</p><button class="btn primary" data-route="explore">Mulai Cari</button></section><section class="section"><div class="section-head"><h2>Kategori</h2><button class="link" data-route="explore">Lihat semua</button></div><div class="grid4">${state.categories.slice(0,8).map(c=>`<div class="cat" data-route="explore"><div class="emoji">${c[0]}</div><span>${c[1]}</span></div>`).join("")}</div></section><section class="section"><div class="section-head"><h2>Rekomendasi</h2><button class="link" data-route="explore">Lihat semua</button></div><div class="hscroll">${state.vendors.map(vendorCard).join("")}</div></section><section class="section banner"><b>🎉 Diskon booking pertama 10%</b><div class="meta">Gunakan kode ENTEGO10 saat checkout.</div></section></main>${bottom("home")}</div>`}
function explore(){return `<div class="phone">${topbar("Jelajahi ENTEGO",true,true)}<main class="content"><div class="tabbar"><button class="tab active">Semua</button><button class="tab">Entertainment</button><button class="tab">Rental</button><button class="tab">Terdekat</button></div>${state.vendors.map(v=>`<div class="card row" data-vendor="${v.id}"><div class="avatar">${v.emoji}</div><div style="flex:1"><div class="row between"><b>${v.name}</b><span class="rating">★ ${v.rating}</span></div><div class="meta">${v.cat} • ${v.loc}</div><div class="row between" style="margin-top:8px"><b>${v.price}</b><span class="pill green">Verified</span></div></div></div>`).join("")}</main>${bottom("explore")}</div>`}
function detail(){const v=state.selectedVendor||state.vendors[0];return `<div class="phone">${topbar(v.name,false,true)}<main class="content"><div class="hero" style="height:220px;display:flex;align-items:flex-end"><div style="font-size:72px">${v.emoji}</div></div><div class="section"><div class="row between"><div><span class="pill">${v.cat}</span><h2 style="margin:8px 0 4px">${v.name}</h2><div class="meta">${v.loc}</div></div><div class="rating">★ ${v.rating}</div></div><div class="divider"></div><div class="row between"><div><div class="meta">Mulai dari</div><div class="price">${v.price}</div></div><span class="pill green">✓ Mitra terverifikasi</span></div></div><section class="section"><h2>Tentang layanan</h2><p class="meta">Paket profesional untuk wedding, private party, corporate event dan kebutuhan entertainment lainnya.</p></section><section class="section"><h2>Paket populer</h2><div class="card"><div class="row between"><div><b>Standard Package</b><div class="meta">3 jam • perlengkapan dasar</div></div><b>${v.price}</b></div></div><div class="card"><div class="row between"><div><b>Premium Package</b><div class="meta">5 jam • prioritas & add-on</div></div><b>Rp3.500.000</b></div></div></section><section class="section"><h2>Ulasan</h2><div class="card">⭐⭐⭐⭐⭐ <b>Profesional & tepat waktu.</b><div class="meta">Kadek • 2 hari lalu</div></div></section></main><div class="sticky-cta"><button class="btn soft" data-route="chat">Chat</button><button class="btn primary" data-route="booking">Booking Sekarang</button></div></div>`}
function booking(){const v=state.selectedVendor||state.vendors[0];return `<div class="phone">${topbar("Booking",false,true)}<main class="content"><div class="card row"><div class="avatar">${v.emoji}</div><div><b>${v.name}</b><div class="meta">${v.cat}</div></div></div><div class="form"><div class="field"><label>Tanggal acara</label><input type="date" value="2026-08-15"></div><div class="field"><label>Jam mulai</label><input type="time" value="19:00"></div><div class="field"><label>Durasi</label><select><option>3 jam</option><option>5 jam</option><option>Full day</option></select></div><div class="field"><label>Lokasi acara</label><input value="Seminyak, Bali"></div><div class="field"><label>Catatan</label><textarea rows="4" placeholder="Detail acara, dress code, request khusus..."></textarea></div></div></main><div class="sticky-cta"><button class="btn primary" data-route="checkout">Lanjut Checkout</button></div></div>`}
function checkout(){return `<div class="phone">${topbar("Checkout",false,true)}<main class="content"><div class="card"><div class="kicker">RINGKASAN BOOKING</div><h3>DJ Raka Bali — Standard Package</h3><div class="meta">15 Agustus 2026 • 19:00 • 3 jam</div><div class="divider"></div><div class="row between"><span>Harga layanan</span><b>Rp1.500.000</b></div><div class="row between"><span>Biaya platform</span><b>Rp75.000</b></div><div class="row between"><span>Promo ENTEGO10</span><b style="color:var(--green)">-Rp150.000</b></div><div class="divider"></div><div class="row between"><b>Total</b><span class="price">Rp1.425.000</span></div></div><div class="card"><b>Metode pembayaran</b><div class="divider"></div><div class="row between"><span>◉ QRIS</span><span class="pill green">Dipilih</span></div></div><div class="banner"><b>🛡️ ENTEGO Protection</b><div class="meta">Pembayaran diteruskan ke mitra setelah layanan selesai sesuai kebijakan platform.</div></div></main><div class="sticky-cta"><button class="btn primary" data-route="orders">Bayar & Buat Order</button></div></div>`}
function orders(){return `<div class="phone">${topbar("Order Saya",false,false)}<main class="content"><div class="tabbar"><button class="tab active">Aktif</button><button class="tab">Selesai</button><button class="tab">Dibatalkan</button></div><div class="card"><div class="row between"><span class="pill blue">#ENT-260815-001</span><span class="pill green">Dikonfirmasi</span></div><h3>🎧 DJ Raka Bali</h3><div class="meta">15 Agu 2026 • 19:00 • Seminyak</div><div class="divider"></div><div class="timeline"><div class="step"><b>Booking dibuat</b><div class="meta">Pembayaran berhasil</div></div><div class="step"><b>Mitra dikonfirmasi</b><div class="meta">DJ Raka menerima booking</div></div><div class="step"><b>Menunggu hari acara</b><div class="meta">Notifikasi H-1 akan dikirim</div></div></div><div class="row"><button class="btn soft" data-route="chat">Chat Mitra</button><button class="btn primary" data-route="orderdetail">Detail</button></div></div></main>${bottom("orders")}</div>`}
function orderdetail(){return `<div class="phone">${topbar("Detail Order",false,true)}<main class="content"><div class="card"><div class="row between"><b>#ENT-260815-001</b><span class="pill green">Dikonfirmasi</span></div><div class="divider"></div><b>DJ Raka Bali</b><div class="meta">15 Agustus 2026 • 19:00 • 3 jam</div></div><div class="card"><b>Lokasi</b><p>Seminyak, Bali</p><button class="btn soft">Buka Maps</button></div><div class="card"><b>Pembayaran</b><div class="row between"><span>QRIS</span><b>Rp1.425.000</b></div></div></main></div>`}
function chat(){return `<div class="phone">${topbar("Chat • DJ Raka",false,true)}<main class="content"><div class="msg">Halo 👋 Terima kasih sudah booking. Ada request lagu atau dress code khusus?</div><div class="msg me">Untuk birthday party. Musik house & commercial ya.</div><div class="msg">Siap. Bisa kirim rundown acaranya di sini nanti.</div></main><div class="sticky-cta"><input style="flex:1;border:1px solid var(--line);border-radius:14px;padding:12px" placeholder="Tulis pesan..."><button class="btn primary">Kirim</button></div></div>`}
function favorites(){return `<div class="phone">${topbar("Favorit",false,false)}<main class="content">${state.vendors.slice(0,2).map(v=>`<div class="card row" data-vendor="${v.id}"><div class="avatar">${v.emoji}</div><div style="flex:1"><b>${v.name}</b><div class="meta">${v.cat} • ${v.loc}</div></div><span>♥</span></div>`).join("")}</main>${bottom("favorites")}</div>`}
function profile(){return `<div class="phone">${topbar("Akun",false,false)}<main class="content"><div class="card row"><div class="avatar">👤</div><div><b>Arda</b><div class="meta">Customer • Bali</div></div></div>${[["🧾","Riwayat transaksi","orders"],["💳","Metode pembayaran","checkout"],["📍","Alamat tersimpan","profile"],["🎁","Voucher & promo","profile"],["🤝","Jadi Mitra ENTEGO","partner"],["⚙️","Pengaturan","profile"],["🛡️","Bantuan & keamanan","profile"],["🧰","Admin Demo","admin"]].map(x=>`<div class="card row between" data-route="${x[2]}"><div class="row"><span>${x[0]}</span><b>${x[1]}</b></div><span>›</span></div>`).join("")}</main>${bottom("profile")}</div>`}
function notifications(){return `<div class="phone">${topbar("Notifikasi",false,true)}<main class="content"><div class="card"><b>✅ Booking dikonfirmasi</b><p class="meta">DJ Raka menerima order kamu untuk 15 Agustus.</p></div><div class="card"><b>🎁 Promo 10%</b><p class="meta">Gunakan ENTEGO10 untuk transaksi pertama.</p></div></main></div>`}
function partner(){return `<div class="phone">${topbar("ENTEGO Mitra",false,true)}<main class="content"><div class="hero"><small>DASHBOARD MITRA</small><h1>Rp12.450.000</h1><p>Pendapatan bulan ini</p><button class="btn primary">Tarik Saldo</button></div><div class="section statgrid"><div class="stat"><span class="meta">Order Aktif</span><b>8</b></div><div class="stat"><span class="meta">Rating</span><b>4.9 ★</b></div><div class="stat"><span class="meta">Views</span><b>1.284</b></div><div class="stat"><span class="meta">Conversion</span><b>18%</b></div></div><section class="section"><div class="section-head"><h2>Order terbaru</h2><button class="link">Semua</button></div><div class="card"><div class="row between"><b>Birthday Party</b><span class="pill green">Baru</span></div><div class="meta">15 Agu • Seminyak • Rp1.500.000</div></div></section><section class="section"><h2>Kelola Bisnis</h2>${["Kalender & ketersediaan","Paket & harga","Portofolio","Ulasan","Dompet & pencairan","Analitik"].map(x=>`<div class="card row between"><b>${x}</b><span>›</span></div>`).join("")}</section></main></div>`}
function admin(){return `<div class="phone">${topbar("ENTEGO Admin",false,true)}<main class="content"><div class="kicker">ADMIN CONTROL CENTER</div><h2>Overview</h2><div class="statgrid"><div class="stat"><span class="meta">Users</span><b>5.240</b></div><div class="stat"><span class="meta">Mitra</span><b>486</b></div><div class="stat"><span class="meta">GMV</span><b>1,2B</b></div><div class="stat"><span class="meta">Booking</span><b>2.084</b></div></div><section class="section"><h2>Operasional</h2>${["Verifikasi Mitra","Booking & Dispute","Pembayaran","Promo & Banner","User Management","Reports & Analytics","CMS & Kategori"].map(x=>`<div class="card row between"><b>${x}</b><span>›</span></div>`).join("")}</section></main></div>`}
function render(){const routes={home,explore,detail,booking,checkout,orders,orderdetail,chat,favorites,profile,notifications,partner,admin};app.innerHTML=(routes[state.route]||home)();bind()}
function bind(){document.querySelectorAll("[data-route]").forEach(el=>el.onclick=()=>{state.route=el.dataset.route;scrollTo(0,0);render()});document.querySelectorAll("[data-vendor]").forEach(el=>el.onclick=()=>{state.selectedVendor=state.vendors.find(v=>v.id==el.dataset.vendor);state.route="detail";scrollTo(0,0);render()})}
render();if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("/sw.js").catch(()=>{}));
