const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'}});
const clean=(v,max=500)=>String(v??'').trim().slice(0,max);
const MAX_BYTES=5*1024*1024;
const ALLOWED=new Map([['image/jpeg','jpg'],['image/png','png'],['image/webp','webp']]);
const configured=env=>Boolean(env.ENT_MEDIA&&typeof env.ENT_MEDIA.put==='function'&&typeof env.ENT_MEDIA.get==='function');
const publicPath=key=>'/media/'+String(key).split('/').map(encodeURIComponent).join('/');
const keyFromPath=path=>path.replace(/^\/media\//,'').split('/').map(decodeURIComponent).join('/');
async function upload(request,env,user){if(!configured(env))return json({ok:false,error:'media_storage_not_configured'},503);if(!user||!['partner','admin'].includes(user.role))return json({ok:false,error:'partner_required'},403);const form=await request.formData().catch(()=>null),file=form?.get('file');if(!file||typeof file.stream!=='function')return json({ok:false,error:'file_required'},400);if(!ALLOWED.has(file.type))return json({ok:false,error:'unsupported_media_type'},415);if(Number(file.size||0)<=0||Number(file.size)>MAX_BYTES)return json({ok:false,error:'media_too_large'},413);const ext=ALLOWED.get(file.type),key=`portfolio/${user.id}/${Date.now()}-${crypto.randomUUID()}.${ext}`;await env.ENT_MEDIA.put(key,file.stream(),{httpMetadata:{contentType:file.type,cacheControl:'public, max-age=31536000, immutable'},customMetadata:{owner:user.id,kind:'portfolio',originalName:clean(file.name,180)}});const origin=new URL(request.url).origin,url=origin+publicPath(key);return json({ok:true,media:{key,url,contentType:file.type,size:file.size}},201)}
async function remove(request,env,user){if(!configured(env))return json({ok:false,error:'media_storage_not_configured'},503);if(!user||!['partner','admin'].includes(user.role))return json({ok:false,error:'partner_required'},403);const url=new URL(request.url),key=clean(url.searchParams.get('key'),500);if(!key.startsWith('portfolio/'))return json({ok:false,error:'invalid_media_key'},400);const head=await env.ENT_MEDIA.head(key);if(!head)return json({ok:true,deleted:false});if(user.role!=='admin'&&head.customMetadata?.owner!==user.id)return json({ok:false,error:'forbidden'},403);await env.ENT_MEDIA.delete(key);return json({ok:true,deleted:true})}
export async function handleMediaApi(request,env,user){const url=new URL(request.url),path=url.pathname;if(path==='/api/media/config'&&request.method==='GET')return json({ok:true,provider:'cloudflare-r2',configured:configured(env),maxBytes:MAX_BYTES,accept:[...ALLOWED.keys()]});if(path==='/api/media/portfolio'&&request.method==='POST')return upload(request,env,user);if(path==='/api/media/portfolio'&&request.method==='DELETE')return remove(request,env,user);return null}
export async function handlePublicMedia(request,env){const url=new URL(request.url);if(!url.pathname.startsWith('/media/'))return null;if(!configured(env))return new Response('Media storage not configured',{status:503,headers:{'cache-control':'no-store'}});if(!['GET','HEAD'].includes(request.method))return new Response('Method Not Allowed',{status:405});const key=keyFromPath(url.pathname);if(!key.startsWith('portfolio/'))return new Response('Not Found',{status:404});const obj=await env.ENT_MEDIA.get(key);if(!obj)return new Response('Not Found',{status:404});const headers=new Headers();if(typeof obj.writeHttpMetadata==='function')obj.writeHttpMetadata(headers);headers.set('etag',obj.httpEtag);headers.set('cache-control','public, max-age=31536000, immutable');headers.set('x-content-type-options','nosniff');return new Response(request.method==='HEAD'?null:obj.body,{status:200,headers})}
