const oq=(s,r=document)=>r.querySelector(s);
function addOpsStyles(){if(oq('#entego-ops-style'))return;const s=document.createElement('style');s.id='entego-ops-style';s.textContent=`.ops-card{background:#fff;border:1px solid #e2e8f0;border-radius:20px;padding:15px;margin:12px 0;box-shadow:0 8px 24px rgba(15,23,42,.05)}.ops-card h3{margin:0 0 6px}.ops-card p{margin:0;color:#64748b;font-size:13px;line-height:1.5}.ops-status{display:inline-flex;padding:6px 9px;border-radius:999px;font-size:11px;font-weight:800;margin-top:10px}.ops-warn{background:#fff7ed;color:#9a3412;border:1px solid #fed7aa}.ops-ok{background:#f0fdf4;color:#166534;border:1px solid #bbf7d0}.ops-actions{display:flex;gap:10px;margin-top:12px}.ops-actions button{flex:1;border-radius:14px;padding:11px;border:1px solid #e2e8f0;background:#fff;font-weight:800}.ops-actions .primary{background:#f97316;color:#fff;border-color:#f97316}.ops-actions .danger{background:#ef4444;color:#fff;border-color:#ef4444}`;document.head.appendChild(s)}
function route(){return localStorage.getItem('entego_route')||'home'}
function disputeOpen(){return localStorage.getItem('entego_dispute_open')==='1'}
function augmentHelp(){if(route()!=='help'||!disputeOpen())return;const m=oq('main.content');if(!m||oq('#opsDisputeHelp'))return;addOpsStyles();const d=document.createElement('div');d.id='opsDisputeHelp';d.className='ops-card';d.innerHTML=`<h3>Dispute aktif #DSP-001</h3><p>${localStorage.getItem('entego_dispute_note')||'Masalah layanan sedang ditinjau.'}</p><span class="ops-status ops-warn">Dana ditahan • Menunggu Admin</span><div class="ops-actions"><button data-ops="admin-dispute">Lihat sebagai Admin</button><button class="primary" data-route="orders">Kembali ke Order</button></div>`;m.prepend(d)}
function augmentAdminDispute(){if(!['admin','adminBookings','adminDispute'].includes(route())||!disputeOpen())return;const m=oq('main.content');if(!m||oq('#opsAdminDispute'))return;addOpsStyles();const d=document.createElement('div');d.id='opsAdminDispute';d.className='ops-card';const resolved=localStorage.getItem('entego_dispute_resolved')==='1';d.innerHTML=resolved?`<h3>Dispute #DSP-001 selesai</h3><p>${localStorage.getItem('entego_dispute_resolution')||'Kasus telah diselesaikan.'}</p><span class="ops-status ops-ok">Resolved</span>`:`<h3>Dispute #DSP-001 perlu review</h3><p>${localStorage.getItem('entego_dispute_note')||'Customer melaporkan masalah layanan.'}</p><span class="ops-status ops-warn">Dana ditahan</span><div class="ops-actions"><button class="danger" data-ops="refund">Refund Customer</button><button class="primary" data-ops="release">Bayar Mitra</button></div>`;m.prepend(d)}
function augmentPartnerWallet(){if(route()!=='partnerWallet')return;const m=oq('main.content');if(!m||oq('#opsPayout'))return;addOpsStyles();const released=localStorage.getItem('entego_payout_released')==='1';const dispute=disputeOpen()&&localStorage.getItem('entego_dispute_resolved')!=='1';const d=document.createElement('div');d.id='opsPayout';d.className='ops-card';d.innerHTML=dispute?`<h3>Payout ditahan</h3><p>Order #ENT-260815-001 sedang dalam proses dispute.</p><span class="ops-status ops-warn">Hold</span>`:released?`<h3>Payout tersedia</h3><p>Customer telah mengonfirmasi layanan. Dana siap dicairkan.</p><span class="ops-status ops-ok">Ready to withdraw</span>`:`<h3>Payout pending</h3><p>Dana dilepas setelah layanan selesai dan dikonfirmasi customer.</p><span class="ops-status ops-warn">Pending</span>`;m.prepend(d)}
function augmentNotifications(){if(route()!=='notifications')return;const m=oq('main.content');if(!m||oq('#opsNotif'))return;addOpsStyles();const d=document.createElement('div');d.id='opsNotif';d.className='ops-card';let text='Order #ENT-260815-001 menunggu perkembangan berikutnya.';if(localStorage.getItem('entego_cancelled')==='1')text='Order dibatalkan. '+(localStorage.getItem('entego_refund_status')||'Refund sedang diproses.');else if(disputeOpen())text='Dispute #DSP-001 aktif. Dana ditahan selama proses review.';else if(localStorage.getItem('entego_payout_released')==='1')text='Transaksi selesai. Dana telah dilepas ke mitra.';else if(localStorage.getItem('entego_completed')==='1')text='Mitra menandai pekerjaan selesai. Mohon konfirmasi layanan.';else if(localStorage.getItem('entego_booking_status')==='diterima')text='Mitra menerima booking kamu.';d.innerHTML=`<h3>Update Transaksi</h3><p>${text}</p>`;m.prepend(d)}
function resolve(kind){localStorage.setItem('entego_dispute_resolved','1');localStorage.setItem('entego_dispute_open','0');if(kind==='refund'){localStorage.setItem('entego_dispute_resolution','Refund disetujui untuk customer');localStorage.setItem('entego_refund_status','Refund disetujui Admin');localStorage.setItem('entego_payout_released','0')}else{localStorage.setItem('entego_dispute_resolution','Pembayaran dilepas ke mitra');localStorage.setItem('entego_payout_released','1');localStorage.setItem('entego_customer_confirmed','1')}location.reload()}
function augment(){augmentHelp();augmentAdminDispute();augmentPartnerWallet();augmentNotifications()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-ops]');if(!b)return;const a=b.dataset.ops;if(a==='admin-dispute'){localStorage.setItem('entego_route','adminDispute');location.reload()}if(a==='refund')resolve('refund');if(a==='release')resolve('release')});
new MutationObserver(augment).observe(document.documentElement,{subtree:true,childList:true});window.addEventListener('load',augment);augment();