import { DurableObject } from "cloudflare:workers";
const clean=(v,max=500)=>String(v??"").trim().slice(0,max);
const money=v=>Math.max(0,Math.round(Number(v)||0));
export class EntegoPartner extends DurableObject{
 constructor(ctx,env){super(ctx,env);this.sql=ctx.storage.sql;this.sql.exec(`
 CREATE TABLE IF NOT EXISTS profiles(user_id TEXT PRIMARY KEY,display_name TEXT NOT NULL,category TEXT NOT NULL DEFAULT '',area TEXT NOT NULL DEFAULT '',specialty TEXT NOT NULL DEFAULT '',bio TEXT NOT NULL DEFAULT '',social TEXT NOT NULL DEFAULT '',price INTEGER NOT NULL DEFAULT 0,cover_url TEXT NOT NULL DEFAULT '',verified INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'active',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS packages(user_id TEXT NOT NULL,id TEXT NOT NULL,name TEXT NOT NULL,duration TEXT NOT NULL DEFAULT '',price INTEGER NOT NULL DEFAULT 0,description TEXT NOT NULL DEFAULT '',featured INTEGER NOT NULL DEFAULT 0,updated_at TEXT NOT NULL,PRIMARY KEY(user_id,id));
 CREATE TABLE IF NOT EXISTS availability(user_id TEXT NOT NULL,date TEXT NOT NULL,status TEXT NOT NULL,note TEXT NOT NULL DEFAULT '',updated_at TEXT NOT NULL,PRIMARY KEY(user_id,date));
 CREATE TABLE IF NOT EXISTS portfolio(user_id TEXT NOT NULL,id TEXT NOT NULL,title TEXT NOT NULL DEFAULT '',url TEXT NOT NULL,featured INTEGER NOT NULL DEFAULT 0,updated_at TEXT NOT NULL,PRIMARY KEY(user_id,id));
 CREATE INDEX IF NOT EXISTS idx_profiles_category ON profiles(category);CREATE INDEX IF NOT EXISTS idx_profiles_area ON profiles(area);CREATE INDEX IF NOT EXISTS idx_profiles_price ON profiles(price);
 `)}
 profileRow(r){return r?{userId:r.user_id,displayName:r.display_name,category:r.category,area:r.area,specialty:r.specialty,bio:r.bio,social:r.social,price:r.price,coverUrl:r.cover_url,verified:Boolean(r.verified),status:r.status,createdAt:r.created_at,updatedAt:r.updated_at}:null}
 async saveProfile(user,input,verified=false){const now=new Date().toISOString(),uid=clean(user,100),display=clean(input.displayName,120);if(!uid||!display)throw new Error('PROFILE_REQUIRED');this.sql.exec(`INSERT INTO profiles(user_id,display_name,category,area,specialty,bio,social,price,cover_url,verified,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET display_name=excluded.display_name,category=excluded.category,area=excluded.area,specialty=excluded.specialty,bio=excluded.bio,social=excluded.social,price=excluded.price,cover_url=excluded.cover_url,verified=excluded.verified,updated_at=excluded.updated_at`,uid,display,clean(input.category,80),clean(input.area,120),clean(input.specialty,160),clean(input.bio,1500),clean(input.social,300),money(input.price),clean(input.coverUrl,1000),verified?1:0,'active',now,now);return this.getProfile(uid)}
 async getProfile(uid){return this.profileRow(this.sql.exec(`SELECT * FROM profiles WHERE user_id=? LIMIT 1`,clean(uid,100)).toArray()[0])}
 async listDirectory(filters={}){const q=clean(filters.q,120).toLowerCase(),cat=clean(filters.category,80),area=clean(filters.area,120),max=money(filters.maxPrice),limit=Math.max(1,Math.min(100,Number(filters.limit)||50));let sql=`SELECT * FROM profiles WHERE status='active'`,args=[];if(q){sql+=` AND (lower(display_name) LIKE ? OR lower(category) LIKE ? OR lower(area) LIKE ? OR lower(specialty) LIKE ?)`;const like=`%${q}%`;args.push(like,like,like,like)}if(cat&&cat!=='all'){sql+=` AND category=?`;args.push(cat)}if(area&&area!=='all'){sql+=` AND area LIKE ?`;args.push(`%${area}%`)}if(max){sql+=` AND price<=?`;args.push(max)}sql+=` ORDER BY verified DESC,updated_at DESC LIMIT ?`;args.push(limit);return this.sql.exec(sql,...args).toArray().map(r=>this.profileRow(r))}
 async savePackages(uid,items=[]){uid=clean(uid,100);const now=new Date().toISOString();this.sql.exec(`DELETE FROM packages WHERE user_id=?`,uid);for(const x of items.slice(0,30)){const id=clean(x.id||crypto.randomUUID(),100),name=clean(x.name,120);if(!name)continue;this.sql.exec(`INSERT INTO packages(user_id,id,name,duration,price,description,featured,updated_at) VALUES(?,?,?,?,?,?,?,?)`,uid,id,name,clean(x.duration,80),money(x.price),clean(x.description,1000),x.featured?1:0,now)}return this.getPackages(uid)}
 async getPackages(uid){return this.sql.exec(`SELECT * FROM packages WHERE user_id=? ORDER BY featured DESC,price ASC`,clean(uid,100)).toArray().map(r=>({id:r.id,name:r.name,duration:r.duration,price:r.price,description:r.description,featured:Boolean(r.featured)}))}
 async saveAvailability(uid,items=[]){uid=clean(uid,100);const now=new Date().toISOString();this.sql.exec(`DELETE FROM availability WHERE user_id=?`,uid);for(const x of items.slice(0,365)){const date=clean(x.date,20),status=clean(x.status,20);if(!date||!['available','unavailable','booked'].includes(status))continue;this.sql.exec(`INSERT INTO availability(user_id,date,status,note,updated_at) VALUES(?,?,?,?,?)`,uid,date,status,clean(x.note,300),now)}return this.getAvailability(uid)}
 async getAvailability(uid){return this.sql.exec(`SELECT date,status,note FROM availability WHERE user_id=? ORDER BY date ASC`,clean(uid,100)).toArray()}
 async savePortfolio(uid,items=[]){uid=clean(uid,100);const now=new Date().toISOString();this.sql.exec(`DELETE FROM portfolio WHERE user_id=?`,uid);for(const x of items.slice(0,24)){const url=clean(x.url||x.src,1000);if(!/^https?:\/\//i.test(url))continue;this.sql.exec(`INSERT INTO portfolio(user_id,id,title,url,featured,updated_at) VALUES(?,?,?,?,?,?)`,uid,clean(x.id||crypto.randomUUID(),100),clean(x.title,160),url,x.featured?1:0,now)}return this.getPortfolio(uid)}
 async getPortfolio(uid){return this.sql.exec(`SELECT id,title,url,featured FROM portfolio WHERE user_id=? ORDER BY featured DESC,updated_at DESC`,clean(uid,100)).toArray().map(r=>({id:r.id,title:r.title,url:r.url,src:r.url,featured:Boolean(r.featured)}))}
 async publicBundle(uid){const profile=await this.getProfile(uid);if(!profile||profile.status!=='active')return null;return {profile,packages:await this.getPackages(uid),availability:await this.getAvailability(uid),portfolio:await this.getPortfolio(uid)}}
}