const RD_ROUTE=()=>localStorage.getItem('entego_route')||'home';
const rdOrder=()=>{try{return JSON.parse(localStorage.getItem('entego_current_order_v2')||'null')}catch{return null}};
const rdUser=()=>{try{return JSON.parse(localStorage.getItem('entego_auth_user')||'null')}catch{return null}};
const rdEsc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const rdTime=v=>{try{return new Date(v).toLocaleString('id-ID',{dateStyle:'medium',timeStyle:'short'})}catch{return '-'}};
async function rdJson(url,options={}){const r=await fetch(url,{cache:'no-store',headers:{accept:'application/json',...(options.headers||{})},...options});let d={};try{d=await r.json()}catch{};return {r,d}}
const rdCheck=(label,ok,note='')=>`<div class="row between" style="gap:10px;padding:8px 0"><div><b style="font-size:13px">${rdEsc(label)}</b>${note?`<div class="meta">${rdEsc(note)}</div>`:''}</div><span class="pill ${ok?'green':'blue'}">${ok?'✓ Siap':'Belum'}</span></div>`;
async function rdRender(force=false){if(!['orderdetail','partnerOrderDetail'].includes(RD_ROUTE()))return;const order=rdOrder(),user=rdUser(),main=document.querySelector('main.content');if(!order?.id||!user||!main)return;let box=document.querySelector('#entegoReadiness');if(box&&!force)return;if(!box){box=document.createElement('section');box.id='entegoReadiness';box.className='card';const participant=document.querySelector('#entegoBookingParticipants');if(participant)participant.after(box);else main.appendChild(box)}box.innerHTML='<div class="kicker">PRE-EVENT READINESS</div><div class="meta">Memeriksa kesiapan booking…</div>';try{const x=await rdJson(`/api/bookings/${encodeURIComponent(order.id)}/readiness`);if(!x.r.ok||!x.d.ok)throw new Error(x.d.error||'load_failed');const r=x.d.readiness,meCheck=(r.checkins||[]).find(c=>c.role===user.role),customer=(r.checkins||[]).find(c=>c.role==='customer'),partner=(r.checkins||[]).find(c=>c.role==='partner');box.innerHTML=`<div class="row between"><div><div class="kicker">PRE-EVENT READINESS</div><h3 style="margin:5px 0">${rdEsc(r.eventDate)} • ${rdEsc(r.eventTime)}</h3></div><span class="pill ${r.disputeOpen?'blue':r.paymentVerified&&r.partnerAccepted?'green':'blue'}">${r.disputeOpen?'Dispute':r.paymentVerified&&r.partnerAccepted?'Protected':'Persiapan'}</span></div><div style="margin-top:8px">${rdCheck('Trust Record',r.agreementRecorded,'Kesepakatan booking tersimpan')}${rdCheck('Persetujuan Mitra',r.partnerAccepted,'Mitra menerima detail yang sama')}${rdCheck('Pembayaran',r.paymentVerified,'Status berasal dari ledger server')}${rdCheck('Tidak ada dispute',!r.disputeOpen,'Dispute menghentikan check-in otomatis')}</div><div class="divider"></div><b>Kehadiran</b><div class="meta" style="margin-top:5px">Check-in adalah timestamp yang dinyatakan sendiri oleh akun ENTEGO. Ini bukan GPS, KYC, atau bukti lokasi absolut.</div><div style="margin-top:8px"><div class="row between"><span>Customer</span><span class="pill ${customer?'green':'blue'}">${customer?`✓ ${rdTime(customer.checkedInAt)}`:'Belum check-in'}</span></div><div class="row between" style="margin-top:7px"><span>Mitra</span><span class="pill ${partner?'green':'blue'}">${partner?`✓ ${rdTime(partner.checkedInAt)}`:'Belum check-in'}</span></div></div>${r.canCheckIn&&!meCheck&&['customer','partner'].includes(user.role)?'<button class="btn primary" id="rdCheckIn" style="width:100%;margin-top:14px">Saya Sudah Hadir</button>':''}${!r.eventToday?'<div class="meta" style="margin-top:10px">Check-in hanya tersedia pada tanggal acara.</div>':''}`;box.querySelector('#rdCheckIn')?.addEventListener('click',()=>rdCheckIn(order.id,box))}catch{box.innerHTML='<div class="kicker">PRE-EVENT READINESS</div><span class="pill blue">Readiness belum dapat dimuat</span><p class="meta">Status kesiapan tidak akan diasumsikan tanpa respons server.</p>'}}
async function rdCheckIn(id,box){const b=box.querySelector('#rdCheckIn');if(!b)return;const old=b.textContent;b.disabled=true;b.textContent='Menyimpan…';try{const x=await rdJson(`/api/bookings/${encodeURIComponent(id)}/checkin`,{method:'POST',headers:{'content-type':'application/json'},body:'{}'});if(!x.r.ok||!x.d.ok)throw new Error(x.d.error||'checkin_failed');await rdRender(true)}catch(e){b.disabled=false;b.textContent=old;const msg={checkin_event_date_only:'Check-in hanya tersedia pada tanggal acara.',payment_required:'Pembayaran belum terverifikasi.',partner_acceptance_required:'Mitra belum menerima booking.',checkin_blocked_by_dispute:'Check-in dikunci selama dispute terbuka.'}[e.message]||'Check-in belum dapat disimpan.';alert(msg)}}
const rdRun=()=>rdRender();new MutationObserver(rdRun).observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('load',rdRun);rdRun();
