const RS_KEY='entego_reschedule_status';
const RS_DATE='entego_reschedule_date';
const RS_TIME='entego_reschedule_time';
function rsEsc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function rsStyle(){if(document.getElementById('entego-rs-style'))return;const s=document.createElement('style');s.id='entego-rs-style';s.textContent=`
.rs-card{background:#fff;border:1px solid #e2e8f0;border-radius:20px;padding:15px;margin:14px 0;box-shadow:0 8px 22px rgba(15,23,42,.05)}.rs-card h3{margin:0 0 8px}.rs-meta{font-size:12px;color:#64748b;line-height:1.5}.rs-actions{display:flex;gap:10px;margin-top:12px}.rs-actions button{flex:1;border-radius:14px;padding:12px;font-weight:800;border:1px solid #e2e8f0;background:#fff}.rs-actions .orange{background:#f97316;color:#fff;border-color:#f97316}.rs-actions .red{background:#fff1f2;color:#be123c;border-color:#fecdd3}.rs-pill{display:inline-flex;border-radius:999px;padding:6px 9px;font-size:11px;font-weight:800;background:#eff6ff;color:#1d4ed8}.rs-sheet{position:fixed;inset:0;z-index:10020;background:rgba(15,23,42,.6);display:flex;align-items:flex-end;justify-content:center}.rs-panel{width:min(100%,480px);background:#f8fafc;border-radius:28px 28px 0 0;padding:18px 18px calc(22px + env(safe-area-inset-bottom))}.rs-panel h2{margin:0 0 6px}.rs-panel p{color:#64748b;font-size:13px}.rs-field{margin-top:12px}.rs-field label{display:block;font-size:12px;font-weight:800;margin-bottom:6px}.rs-field input{width:100%;box-sizing:border-box;border:1px solid #dbe3ec;border-radius:14px;padding:13px;background:#fff;font-size:15px}.rs-note{background:#fff7ed;border:1px solid #fed7aa;border-radius:15px;padding:12px;margin-top:12px;font-size:12px;color:#9a3412;line-height:1.45}
`;document.head.appendChild(s)}
function rsRoute(){return localStorage.getItem('entego_route')||'home'}
function rsEligible(){return localStorage.getItem('entego_cancelled')!=='1'&&localStorage.getItem('entego_completed')!=='1'&&localStorage.getItem('entego_event_started')!=='1'}
function openReschedule(){rsStyle();if(!rsEligible()){alert('Jadwal tidak dapat diubah setelah pekerjaan dimulai atau order ditutup.');return}const o=document.createElement('div');o.className='rs-sheet';o.innerHTML=`<div class="rs-panel"><h2>Ubah Jadwal</h2><p>Ajukan tanggal dan jam baru. Mitra akan menerima notifikasi dan perlu mengonfirmasi perubahan.</p><div class="rs-field"><label>Tanggal baru</label><input id="rsDate" type="date" value="${rsEsc(localStorage.getItem(RS_DATE)||'2026-08-16')}"></div><div class="rs-field"><label>Jam baru</label><input id="rsTime" type="time" value="${rsEsc(localStorage.getItem(RS_TIME)||'20:00')}"></div><div class="rs-note">Jadwal lama tetap berlaku sampai mitra menyetujui permintaan perubahan.</div><div class="rs-actions"><button id="rsClose">Kembali</button><button class="orange" id="rsSubmit">Ajukan Perubahan</button></div></div>`;document.body.appendChild(o);o.addEventListener('click',e=>{if(e.target===o||e.target.id==='rsClose')o.remove()});o.querySelector('#rsSubmit').onclick=()=>{const d=o.querySelector('#rsDate').value,t=o.querySelector('#rsTime').value;if(!d||!t){alert('Pilih tanggal dan jam baru.');return}localStorage.setItem(RS_DATE,d);localStorage.setItem(RS_TIME,t);localStorage.setItem(RS_KEY,'pending');o.remove();location.reload()}}
function formatRsDate(v){if(!v)return'-';try{return new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'long',year:'numeric'}).format(new Date(v+'T00:00:00'))}catch{return v}}
function addCustomerReschedule(){if(rsRoute()!=='orderdetail')return;const main=document.querySelector('main.content');if(!main||document.getElementById('rsCustomer'))return;const status=localStorage.getItem(RS_KEY)||'';const c=document.createElement('div');c.id='rsCustomer';c.className='rs-card';if(!status&&rsEligible()){c.innerHTML=`<h3>Perlu ubah jadwal?</h3><div class="rs-meta">Kamu dapat mengajukan perubahan tanggal/jam selama pekerjaan belum dimulai.</div><div class="rs-actions"><button class="orange" id="rsOpen">Ubah Jadwal</button></div>`}else if(status==='pending'){c.innerHTML=`<span class="rs-pill">Menunggu Mitra</span><h3 style="margin-top:10px">Permintaan perubahan jadwal</h3><div class="rs-meta">${formatRsDate(localStorage.getItem(RS_DATE))} • ${rsEsc(localStorage.getItem(RS_TIME))}<br>Jadwal lama tetap aktif sampai disetujui.</div><div class="rs-actions"><button class="red" id="rsCancelRequest">Batalkan Permintaan</button></div>`}else if(status==='approved'){c.innerHTML=`<span class="rs-pill" style="background:#f0fdf4;color:#15803d">Disetujui</span><h3 style="margin-top:10px">Jadwal baru dikonfirmasi</h3><div class="rs-meta">${formatRsDate(localStorage.getItem(RS_DATE))} • ${rsEsc(localStorage.getItem(RS_TIME))}</div>`}else if(status==='rejected'){c.innerHTML=`<span class="rs-pill" style="background:#fff1f2;color:#be123c">Ditolak</span><h3 style="margin-top:10px">Mitra belum bisa di jadwal baru</h3><div class="rs-meta">Kamu dapat mengajukan jadwal lain atau chat mitra.</div><div class="rs-actions"><button class="orange" id="rsOpen">Ajukan Lagi</button></div>`}main.appendChild(c);c.querySelector('#rsOpen')?.addEventListener('click',openReschedule);c.querySelector('#rsCancelRequest')?.addEventListener('click',()=>{localStorage.removeItem(RS_KEY);localStorage.removeItem(RS_DATE);localStorage.removeItem(RS_TIME);location.reload()})}
function addPartnerReschedule(){if(!['partner','partnerOrders','partnerOrderDetail'].includes(rsRoute()))return;if(localStorage.getItem(RS_KEY)!=='pending')return;const main=document.querySelector('main.content');if(!main||document.getElementById('rsPartner'))return;const c=document.createElement('div');c.id='rsPartner';c.className='rs-card';c.innerHTML=`<span class="rs-pill">Perubahan Jadwal</span><h3 style="margin-top:10px">Customer mengajukan jadwal baru</h3><div class="rs-meta">${formatRsDate(localStorage.getItem(RS_DATE))} • ${rsEsc(localStorage.getItem(RS_TIME))}</div><div class="rs-actions"><button class="red" id="rsReject">Tolak</button><button class="orange" id="rsApprove">Setujui</button></div>`;main.prepend(c);c.querySelector('#rsApprove').onclick=()=>{localStorage.setItem(RS_KEY,'approved');location.reload()};c.querySelector('#rsReject').onclick=()=>{localStorage.setItem(RS_KEY,'rejected');location.reload()}}
function rsAugment(){rsStyle();addCustomerReschedule();addPartnerReschedule()}
new MutationObserver(rsAugment).observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('load',rsAugment);rsAugment();