const CACHE="entego-v68";
const DIRECTORY_CACHE="entego-directory-v68";
const DIRECTORY_TTL_MS=120000;
const SHELL=["/","/manifest.webmanifest?v=67","/icon-192.png?v=67","/icon-512.png?v=67","/icon-maskable-512.png?v=67","/apple-touch-icon.png?v=67","/logo-header.png?v=67","/production-truth-gate-flow.js?v=67","/production-guard-flow.js?v=67","/route-loader-flow.js?v=67"];
self.addEventListener("install",event=>{self.skipWaiting();event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(SHELL)))});
self.addEventListener("activate",event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>![CACHE,DIRECTORY_CACHE].includes(key)).map(key=>caches.delete(key)))).then(()=>self.clients.claim()))});
async function cacheFirst(request){const cache=await caches.open(CACHE),hit=await cache.match(request);if(hit)return hit;const response=await fetch(request);if(response.ok)cache.put(request,response.clone());return response}
async function staleWhileRevalidate(request){const cache=await caches.open(CACHE),hit=await cache.match(request);const network=fetch(request).then(response=>{if(response.ok)cache.put(request,response.clone());return response}).catch(()=>null);return hit||await network||await cache.match("/")}
async function directoryResponse(request,event){const cache=await caches.open(DIRECTORY_CACHE),hit=await cache.match(request),cachedAt=hit?Date.parse(hit.headers.get("date")||""):NaN;const fresh=hit&&Number.isFinite(cachedAt)&&Date.now()-cachedAt<=DIRECTORY_TTL_MS;const network=fetch(request).then(async response=>{if(response.ok)await cache.put(request,response.clone());return response});if(fresh){event.waitUntil(network.catch(()=>null));return hit}try{return await network}catch{return new Response(JSON.stringify({ok:false,error:"directory_unavailable"}),{status:503,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}})}}
self.addEventListener("fetch",event=>{if(event.request.method!=="GET")return;const url=new URL(event.request.url);if(url.origin===self.location.origin&&url.pathname==="/api/directory"){event.respondWith(directoryResponse(event.request,event));return}if(url.pathname.startsWith("/api/")||url.pathname.startsWith("/media/"))return;if(event.request.mode==="navigate"){event.respondWith(staleWhileRevalidate(event.request));return}if(url.origin===self.location.origin){event.respondWith(cacheFirst(event.request));return}});
